apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 32000  # Example NodePort, this can be any available port in the range 30000-32767
  selector:
    app: mongo